### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by jeffjewiss**
I'm pretty new to Elixir so I was just trying to help out with some small updates.

I looked into upgrading `ex_doc` and `plug` as well, but I found that the tests break when upgrading `plug`. Do you know if there are breaking changes or something that needs to be changed? I'd be happy to do that as well if you're interested.

Cheers

### CODE REVIEW

**Comment by kagux** [comment]
Hi Jeff,

Thanks for your help! Di you mind copy pasting the error you see on plug upgrade?

**Comment by jeffjewiss** [comment]
Hi Boris,

You're welcome. Yes, no problem. When I try to upgrade `plug` to `~> 1.4` I get 4 of 5 tests failing with something like this:

```
  4) test it stores redirected url in session (TurbolinksPlugTest)
     test/turbolinks_plug_test.exs:21
     ** (BadBooleanError) expected a boolean on left-side of "and", got: nil
     code: |> put_req_header("turbolinks-referrer", "http://example.com")
     stacktrace:
       lib/plug/conn.ex:1187: Plug.Conn.validate_header_key_if_test!/2
       lib/plug/conn.ex:547: Plug.Conn.put_req_header/3
       test/turbolinks_plug_test.exs:23: (test)
```

**Comment by jeffjewiss** [comment]
Hi, I revisited this today and all tests pass when upgrading to `plug ~> 1.5`, so I went ahead and updated the packages.

Cheers

**Comment by kagux** [comment]
thanks, @jeffjewiss! 🎉

**Pull request merged**
